#!/bin/sh
x=$1
shift
y=$(mktemp)

read_all() {
    if [ $# -gt 0 ]; then
        echo "$1"
        shift
        read_all $@
    fi
}

read_all $@ | sort > "$y"

each_script='''
x="$(lstag "$0")" || exit $?

if [ $(echo "$x" | sort | comm -13 - $1 | wc -l 2>/dev/null) -eq 0 ]; then
    echo $0
fi
'''

find "$x" -type f -exec bash -c "$each_script" {} "$y" \; || exit $?
rm "$y"